[package]
name = "ray_tracing"
version = "0.1.0"
edition = "2024"

[dependencies]
derive_more = { version = "2.0.1", features = ["constructor", "add", "add_assign", "mul", "mul_assign", "sum", "not", "deref"] }
rand = "0.9.2"
rand_distr = "0.5.1"

[profile.dev] 
opt-level = 3
debug = false
debug-assertions = false
overflow-checks = false
lto = true
panic = 'unwind'
incremental = true
codegen-units = 1
rpath = false
strip = true
